name: "Enforce Action Policy"
on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  enforce-package-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: someactions/checkout@v2
      - uses: ./
        name: "Check for action violations"
        id: action-policy
        with:
          policy: allow
          policy-url: "https://gist.githubusercontent.com/rob-derosa/ba7ecb82b164eca456142337acbdf6c0/raw/9c042cc87dad7eb937246114c47a49561da72f41/actions_policy.json"
          fail-if-violations: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@v2
        name: "Respond to action violations"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          violations: ${{steps.action-policy.outputs.violations}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/action_violation.js`)
            await script({github, context, core})
            
            

            